import BrandLogo from '@/components/common/BrandLogo'
import { invoiceNumber, money } from '@/utils/documents'

export default function RentalInvoice({ invoice }) {
  if (!invoice) return null

  const number = invoice.number || invoiceNumber({ id: invoice.id, date: invoice.issueDate })
  const items = invoice.items?.length
    ? invoice.items
    : [{ description: `Monthly rent — ${invoice.period}`, amount: invoice.amount }]
  const total = items.reduce((sum, item) => sum + Number(item.amount || 0), 0)
  const paid = invoice.status === 'paid'

  return (
    <article className="print-sheet mx-auto w-full max-w-[800px] bg-white p-8 text-gray-900">
      <header className="flex items-start justify-between gap-6 border-b border-gray-200 pb-6">
        <div>
          <BrandLogo className="h-12 w-auto" />
          <p className="mt-2 text-xs font-semibold uppercase tracking-wider text-gray-400">
            Property Rental System
          </p>
          <p className="mt-1 text-sm text-gray-500">Phnom Penh, Cambodia</p>
        </div>
        <div className="text-right">
          <p className="text-xs font-semibold uppercase tracking-wider text-gray-400">Invoice</p>
          <p className="mt-1 text-lg font-bold text-forest">{number}</p>
          <p className="mt-1 text-sm text-gray-500">Issued {invoice.issueDate}</p>
          <span
            className={`mt-2 inline-flex rounded-full px-2.5 py-1 text-xs font-semibold ${
              paid ? 'bg-green-50 text-green-700' : 'bg-amber-50 text-amber-700'
            }`}
          >
            {paid ? 'Paid' : 'Due'}
          </span>
        </div>
      </header>

      <div className="mt-6 grid grid-cols-2 gap-6 text-sm">
        <div>
          <p className="text-xs font-semibold uppercase tracking-wider text-gray-400">From (Landlord)</p>
          <p className="mt-1 font-semibold text-gray-900">{invoice.landlord}</p>
          {invoice.landlordContact && <p className="text-gray-500">{invoice.landlordContact}</p>}
        </div>
        <div>
          <p className="text-xs font-semibold uppercase tracking-wider text-gray-400">Bill to (Tenant)</p>
          <p className="mt-1 font-semibold text-gray-900">{invoice.tenant}</p>
          {invoice.tenantContact && <p className="text-gray-500">{invoice.tenantContact}</p>}
        </div>
      </div>

      <div className="mt-6 rounded-xl bg-cream/80 px-4 py-3 text-sm">
        <p className="font-semibold text-gray-900">{invoice.propertyTitle}</p>
        <p className="text-gray-500">{invoice.propertyAddress}</p>
        <p className="mt-1 text-gray-600">Rental period: {invoice.period}</p>
      </div>

      <table className="mt-6 w-full text-sm">
        <thead>
          <tr className="border-b border-gray-200 text-left text-xs uppercase tracking-wider text-gray-400">
            <th className="pb-2 font-semibold">Description</th>
            <th className="pb-2 text-right font-semibold">Amount</th>
          </tr>
        </thead>
        <tbody>
          {items.map((item, i) => (
            <tr key={i} className="border-b border-gray-100">
              <td className="py-3 text-gray-700">{item.description}</td>
              <td className="py-3 text-right font-medium text-gray-900">{money(item.amount)}</td>
            </tr>
          ))}
        </tbody>
        <tfoot>
          <tr>
            <td className="pt-4 text-right font-semibold text-gray-900">Total</td>
            <td className="pt-4 text-right text-lg font-bold text-forest">{money(total)}</td>
          </tr>
        </tfoot>
      </table>

      <div className="mt-6 grid grid-cols-2 gap-4 text-sm">
        <p>
          <span className="text-gray-400">Payment method</span>
          <br />
          <span className="font-medium text-gray-900">
            {invoice.method === 'cash' ? 'Cash' : 'ABA QR'}
          </span>
        </p>
        {invoice.paidDate && (
          <p>
            <span className="text-gray-400">Paid on</span>
            <br />
            <span className="font-medium text-gray-900">{invoice.paidDate}</span>
          </p>
        )}
      </div>

      <p className="mt-8 text-xs leading-relaxed text-gray-400">
        This is a rental invoice generated by PRS for record-keeping. Keep a copy for your lease
        file. For questions, contact the landlord listed above.
      </p>
    </article>
  )
}
